### ISSUE TITLE
Error Syntax

### ISSUE THREAD

**Issue by sprabowo** [dwisiswant0/apkleaks#1]
**Command:**
python apkleaks.py -f file_name.apk

**OS version:**
OSX High Sierra

**Python version:**
3.8.0

**Screenshoot**
<img width="729" alt="Screen Shot 2020-05-31 at 11 37 18" src="https://user-images.githubusercontent.com/11748183/83344633-c01ce480-a333-11ea-966f-6698b9d8b53e.png">

**Comment by dwisiswant0** [comment]
Run with `python2`.
