### ISSUE TITLE
Issue with requirements.txt (numpy) installation

### ISSUE THREAD

**Issue by mdisrail2468** [dwisiswant0/apkleaks#19]
I've been trying to install APKLeaks but having some run time installation error while installing the `requirement.text`. It seems there's some error with numpy cause it's failing to build and clean wheel again and again.

I even tried updating numpy to the latest version and re-installing too but there's no success. Please find the entire error here: https://ghostbin.co/paste/ojqknqs/raw

**Comment by dwisiswant0** [comment]
Please try with `pip3 install numpy`. Let me know what it'll look like.

**Comment by mdisrail2468** [comment]
$pip3 install numpy

Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (1.19.5)
