### ISSUE TITLE
Module Error

### ISSUE THREAD

**Issue by xxnbyy** [dwisiswant0/apkleaks#2]
![image](https://user-images.githubusercontent.com/20261647/83348041-d6d73180-a35b-11ea-946e-92b2e34c3285.png)
What's the apk_parse.apk module?I can't find this

**Comment by dwisiswant0** [comment]
You're missing to install requirements step.

**Comment by dwisiswant0** [comment]
Hi @xxnbyy, now APKLeaks is released version 2 (that supports Python3). Please give it try! No more this kinds of issues.
