### ISSUE TITLE
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

### ISSUE THREAD

**Issue by JonhSilver** [dwisiswant0/apkleaks#22]
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

**Comment by dwisiswant0** [comment]
The error message is pretty clear.

**Comment by JonhSilver** [comment]
but java installed and JAVA_HOME are setted in environment

**Comment by dwisiswant0** [comment]
> but java jdk installed and JAVA_HOME are setted in environment

```console
$ export PATH=$PATH:$JAVA_HOME
```

**Comment by JonhSilver** [comment]
im on Windows 8

**Comment by JonhSilver** [comment]
if run jadx.bat alone it working perfect, but when it started by python it cant find envirotment

**Comment by dwisiswant0** [comment]
AH, Windows things. At first I didn't think it would be, reopening this issue while investigate it.
> I'll be back to you as tester on Windows environment.

**Comment by fuuman** [comment]
Had the exact same issue. Set JAVA_HOME, reboot PC, worked.

**Comment by dwisiswant0** [comment]
> Had the exact same issue. Set JAVA_HOME, reboot PC, worked.

cc: @JonhSilver
