### ISSUE TITLE
Empty results in Windows

### ISSUE THREAD

**Issue by fuuman** [dwisiswant0/apkleaks#24]
I just called `python apkleaks.py -f app.apk -o app.txt` and got:

>  Scanning APK file for URIs, endpoints & secrets
>  (c) 2020-2021, dwisiswant0
> ←[0m
> ←[94m** Decompiling APK...
> ←[0mINFO  - loading ...
> INFO  - processing ...
> ERROR - finished with errors, count: 3

The `app.txt` file is completly empty. What could be the problem? 

OS: Windows 10
Python: 3.8.0

**Comment by dwisiswant0** [comment]
Had you try with another APK file that caused empty results?

**Comment by fuuman** [comment]
I've tried two other APKs. Similar output. For example:

>  Scanning APK file for URIs, endpoints & secrets
 (c) 2020-2021, dwisiswant0
←[0m
←[94m** Decompiling APK...
←[0mINFO  - loading ...
INFO  - processing ...
ERROR - finished with errors, count: 11

**Comment by dwisiswant0** [comment]
Is there no one leaked stuffs that printed out?

**Comment by amaan-ahmad** [comment]
hey @dwisiswant0, the same happened with me  and it went on like this:

`
INFO  - loading ...
INFO  - processing ...
ERROR - finished with errors, count: 1
`

then the output file was empty.

**Comment by dwisiswant0** [comment]
Hey, @amaan-ahmad & @fuuman. Can you please reproduce on `v2.0.8`? Let me know then.

**Comment by sashamiliatin** [comment]
1. mimetypes.guess_type(filepath)[0] return None for all files so I committed this one 
2. open(filepath,encoding="utf8") , add encoding , some files Throwing an error
![Capture1111](https://user-images.githubusercontent.com/34767366/111917275-cda08800-8a87-11eb-8e29-8bfe55f0ae39.PNG)

**Comment by dwisiswant0** [comment]
> 1. mimetypes.guess_type(filepath)[0] return None for all files so I committed this one
> 2. open(filepath,encoding="utf8") , add encoding , some files Throwing an error
>    ![Capture1111](https://user-images.githubusercontent.com/34767366/111917275-cda08800-8a87-11eb-8e29-8bfe55f0ae39.PNG)

Can you please try with `v2.1.0`?

**Comment by sashamiliatin** [comment]
> > 1. mimetypes.guess_type(filepath)[0] return None for all files so I committed this one
> > 2. open(filepath,encoding="utf8") , add encoding , some files Throwing an error
> >    ![Capture1111](https://user-images.githubusercontent.com/34767366/111917275-cda08800-8a87-11eb-8e29-8bfe55f0ae39.PNG)
> 
> Can you please try with `v2.1.0`?

firs of all :
args = [self.jadx, self.file, "-d", self.tempdir, "--deobf"]
		comm = "%s" % (" ".join(quote(arg) for arg in args))
givs an errore
i changet it to comm = "%s %s -d %s --deobf" % (self.jadx, self.file, self.tempdir)
and empty file yet
![image](https://user-images.githubusercontent.com/34767366/111918610-9d101c80-8a8e-11eb-8ac4-8d1e968b7850.png)

**Comment by sashamiliatin** [comment]
> > > 1. mimetypes.guess_type(filepath)[0] return None for all files so I committed this one
> > > 2. open(filepath,encoding="utf8") , add encoding , some files Throwing an error
> > >    ![Capture1111](https://user-images.githubusercontent.com/34767366/111917275-cda08800-8a87-11eb-8e29-8bfe55f0ae39.PNG)
> > 
> > 
> > Can you please try with `v2.1.0`?
> 
> firs of all :
> args = [self.jadx, self.file, "-d", self.tempdir, "--deobf"]
> comm = "%s" % (" ".join(quote(arg) for arg in args))
> givs an errore
> i changet it to comm = "%s %s -d %s --deobf" % (self.jadx, self.file, self.tempdir)
> and its works!!!! thanks
![image](https://user-images.githubusercontent.com/34767366/111918851-b1a0e480-8a8f-11eb-8031-cf8b7b5ca654.png)
