### ISSUE TITLE
Results should be shown on stdout

### ISSUE THREAD

**Issue by tautology0** [dwisiswant0/apkleaks#26]
It always saves results to a file which makes it difficult to grep against and goes against the UX for virtually all *ix interfaces. The logic is sort of turned about - you should output to stdout unless a filename is supplied (using a --output option).

**Comment by dwisiswant0** [comment]
By default it will be sent to `stdout`, and I've also added a JSON format for output _(if you use the 'dev' branch or the v2.0.6-dev equivalent)_. So the temporary output will not be interrupted.
