### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by adapana** [dwisiswant0/apkleaks#29]
I used the following command,

`python apkleaks.py -f testapp.apk`

but it gives error : 

> ←[0m
> ←[94m** Decompiling APK...
> ←[0mThe filename, directory name, or volume label syntax is incorrect.
> 
> ** Scanning against 'instagram.photo.video.downloader.repost.insta'
> 
> ** Done with nothing. ¯\_(ツ)_/¯

**Comment by dwisiswant0** [comment]
Hey, are you running on Windows, @adapana?

**Comment by adapana** [comment]
Yes

**Comment by dwisiswant0** [comment]
Should be fixed on `v2.1.0` and above.
