### ISSUE TITLE
ApkLeaks does not decompile all DEX files

### ISSUE THREAD

**Issue by U039b** [dwisiswant0/apkleaks#30]
The code reveals that ApkLeaks only decompiles `classes.dex`, omitting any other DEX files: https://github.com/dwisiswant0/apkleaks/blob/master/apkleaks/apkleaks.py#L92

Since `jadx` is able to decompile an entire APK file, I suggest to pass the following arguments to `jadx`:
```python
args = [self.jadx, self.file, "-d", self.tempdir, "--deobf"]
```

**Comment by U039b** [comment]
Hi @dwisiswant0! Do you have any comments on this issue?

**Comment by dwisiswant0** [comment]
What did you think that any other `dex` files is different, @U039b? Aren't `classes` is the main dex of an APK? Please correct me if I'm wrong.

**Comment by U039b** [comment]
Due to an Android limitation, large applications use multiple DEX files as you can see here https://beta.pithus.org/report/510b648ffcc5b00af8a0715b52abc46b9cae8c65766d1944784c55e11b0b7d94
DEX files are named as follow:
- `classes.dex`
- `classes2.dex`
- ...
