### ISSUE TITLE
Can't create directory/permission denied

### ISSUE THREAD

**Issue by srzern** [dwisiswant0/apkleaks#54]
When i use --outpot, i get this error:
`PermissionError: [Errno 13] Permission denied: 'C:\\Users\\sezer\\Desktop\\folder'`

When use just -f file.apk, i get this one:
``` 
ERROR - Error saving class: com.things.thing
jadx.core.utils.exceptions.JadxRuntimeException: 
Can't create directory C:\Users\sezer\AppData\Local\Temp\apkleaks-woqqyysy\sources\com\exampleapk\module\ui\main\api\data\aux
______________________________________________________________________________________________
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\sezer\\AppData\\Local\\Temp\\apkleaks-3hmqctov.txt'
``` 

I tried use on admin mode too but still same.

**Comment by dwisiswant0** [comment]
What step when the error appears, @srzern? No error line is shown, you also snipped the output.

**Comment by srzern** [comment]
Thanks for answer,
``` 
** Decompiling APK...
INFO  - loading ...
INFO  - processing ...
ERROR - finished with errors, count: 12

** Scanning against 'ru.iptvremote.android.iptv'
```

I restart windows using recovery and install again. I tried a apk and first one give error but when scan against its worked

**Comment by dwisiswant0** [comment]
That's the output from the decompiler. Closing now.
