### ISSUE TITLE
ERROR - finished with errors, count: 146

### ISSUE THREAD

**Issue by fhartavi** [dwisiswant0/apkleaks#64]
v2.6.1
 --
 Scanning APK file for URIs, endpoints & secrets
 (c) 2020-2021, dwisiswant0
[0m
[94m** Decompiling APK...
[0mINFO  - loading ...
INFO  - processing ...
ERROR - finished with errors, count: 146

**Comment by rakshith111** [comment]
i think this is jadx problem try running it with latest jadx version

**Comment by Drjacky** [comment]
jadx is the latest version, 1.5.3 and still:
`ERROR - finished with errors, count: 58`
