### ISSUE TITLE
ERROR:  No module named apk_parse.apk

### ISSUE THREAD

**Issue by DIEGOD79** [dwisiswant0/apkleaks#7]
Hi, i'm having this error while trying to run the script:

# python2 apkleaks.py -h
Traceback (most recent call last):
  File "apkleaks.py", line 2, in <module>
    from apk_parse.apk import APK
ImportError: No module named apk_parse.apk

Where can i find this "apk_parse.apk" file ?

Thanks

**Comment by teslatheg0d** [comment]
Same issue with me...

**Comment by dwisiswant0** [comment]
Hi, y'all need to install required dependencies. Please note that APKLeaks only works on Python2.7 environment.

```
pip2 install -r requirements.txt
```

Then run,
```
python2.7 apkleaks.py [args...]
```

**Comment by teslatheg0d** [comment]
```
└─# python2.7 apkleaks.py -h         
Traceback (most recent call last):
  File "apkleaks.py", line 2, in <module>
    from apkleaks.apkleaks import apkleaks
  File "/root/tools/apk_recon/apkleaks/apkleaks/apkleaks.py", line 2, in <module>
    from apk_parse.apk import APK
ImportError: No module named apk_parse.apk

```

Still not working

**Comment by jlittlecameo** [comment]
I got the same issue.

**Comment by JonLittleIT** [comment]
I got the same issue still.

**Comment by JonLittleIT** [comment]
> ```
> └─# python2.7 apkleaks.py -h         
> Traceback (most recent call last):
>   File "apkleaks.py", line 2, in <module>
>     from apkleaks.apkleaks import apkleaks
>   File "/root/tools/apk_recon/apkleaks/apkleaks/apkleaks.py", line 2, in <module>
>     from apk_parse.apk import APK
> ImportError: No module named apk_parse.apk
> ```
> 
> Still not working

I got the same issue.

**Comment by Terxeno** [comment]
Use
**pip2.7 install -r requirements.txt**
and then
**python2.7 apkleaks.py**

**Comment by EstherZurita** [comment]
HI, I tried the solution that indicates, but it does not work for me, I attach the log:

@kali:~/apkleaks# pip2.7 install -r requirements.txt
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip                               21.0 will drop support for Python 2.7 in January 2021. More details abou                              t Python 2 support in pip can be found at https://pip.pypa.io/en/latest/                              development/release-process/#python-2-support pip 21.0 will remove suppo                              rt for this functionality.                                                                            
Requirement already satisfied: numpy in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (1.16.5)
Requirement already satisfied: mock in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (3.0.5)
Collecting m2crypto
  Using cached M2Crypto-0.37.1.tar.gz (1.2 MB)
Processing /root/.cache/pip/wheels/b6/b6/b0/c55ca50ab21e84170567278ea3e44082cc8483a94a95f79183/apk_parse_ph4-0.1.8-py2.py3-none-any.whl
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from mock->-r requirements.txt (line 2)) (1.15.0)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in /usr/local/lib/python2.7/dist-packages (from mock->-r requirements.txt (line 2)) (1.0.2)
Requirement already satisfied: typing in /usr/local/lib/python2.7/dist-packages (from m2crypto->-r requirements.txt (line 3)) (3.7.4.3)
Building wheels for collected packages: m2crypto
  Building wheel for m2crypto (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python2 -u -c 'import sys, setuptools, tokenize; sy                              s.argv[0] = '"'"'/tmp/pip-install-K3Qabx/m2crypto/setup.py'"'"'; __file_                              _='"'"'/tmp/pip-install-K3Qabx/m2crypto/setup.py'"'"';f=getattr(tokenize                              , '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',                               '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' b                              dist_wheel -d /tmp/pip-wheel-PtnbHI                                                                   
       cwd: /tmp/pip-install-K3Qabx/m2crypto/                                                         
  Complete output (55 lines):                                                                         
  running bdist_wheel                                                                                 
  running build                                                                                       
  running build_py                                                                                    
  copying M2Crypto/m2.py -> build/lib.linux-x86_64-2.7/M2Crypto                                       
  copying M2Crypto/X509.py -> build/lib.linux-x86_64-2.7/M2Crypto                                     
  copying M2Crypto/threading.py -> build/lib.linux-x86_64-2.7/M2Crypto                                
  copying M2Crypto/DH.py -> build/lib.linux-x86_64-2.7/M2Crypto                                       
  copying M2Crypto/util.py -> build/lib.linux-x86_64-2.7/M2Crypto                                     
  copying M2Crypto/six.py -> build/lib.linux-x86_64-2.7/M2Crypto                                      
  copying M2Crypto/ftpslib.py -> build/lib.linux-x86_64-2.7/M2Crypto                                  
  copying M2Crypto/m2urllib.py -> build/lib.linux-x86_64-2.7/M2Crypto                                 
  copying M2Crypto/__init__.py -> build/lib.linux-x86_64-2.7/M2Crypto                                 
  copying M2Crypto/callback.py -> build/lib.linux-x86_64-2.7/M2Crypto                                 
  copying M2Crypto/m2urllib2.py -> build/lib.linux-x86_64-2.7/M2Crypto                                
  copying M2Crypto/DSA.py -> build/lib.linux-x86_64-2.7/M2Crypto                                      
  copying M2Crypto/Err.py -> build/lib.linux-x86_64-2.7/M2Crypto                                      
  copying M2Crypto/m2xmlrpclib.py -> build/lib.linux-x86_64-2.7/M2Crypto                              
  copying M2Crypto/AuthCookie.py -> build/lib.linux-x86_64-2.7/M2Crypto                               
  copying M2Crypto/RC4.py -> build/lib.linux-x86_64-2.7/M2Crypto                                      
  copying M2Crypto/m2crypto.py -> build/lib.linux-x86_64-2.7/M2Crypto                                 
  copying M2Crypto/Rand.py -> build/lib.linux-x86_64-2.7/M2Crypto                                     
  copying M2Crypto/EVP.py -> build/lib.linux-x86_64-2.7/M2Crypto                                      
  copying M2Crypto/EC.py -> build/lib.linux-x86_64-2.7/M2Crypto                                       
  copying M2Crypto/httpslib.py -> build/lib.linux-x86_64-2.7/M2Crypto                                 
  copying M2Crypto/RSA.py -> build/lib.linux-x86_64-2.7/M2Crypto                                      
  copying M2Crypto/SMIME.py -> build/lib.linux-x86_64-2.7/M2Crypto                                    
  copying M2Crypto/ASN1.py -> build/lib.linux-x86_64-2.7/M2Crypto                                     
  copying M2Crypto/BIO.py -> build/lib.linux-x86_64-2.7/M2Crypto                                      
  copying M2Crypto/Engine.py -> build/lib.linux-x86_64-2.7/M2Crypto                                   
  copying M2Crypto/BN.py -> build/lib.linux-x86_64-2.7/M2Crypto                                       
  creating build/lib.linux-x86_64-2.7/M2Crypto/SSL                                                    
  copying M2Crypto/SSL/TwistedProtocolWrapper.py -> build/lib.linux-x86_                              64-2.7/M2Crypto/SSL                                                                                   
  copying M2Crypto/SSL/Session.py -> build/lib.linux-x86_64-2.7/M2Crypto                              /SSL                                                                                                  
  copying M2Crypto/SSL/Checker.py -> build/lib.linux-x86_64-2.7/M2Crypto                              /SSL                                                                                                  
  copying M2Crypto/SSL/Context.py -> build/lib.linux-x86_64-2.7/M2Crypto                              /SSL                                                                                                  
  copying M2Crypto/SSL/cb.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL                               
  copying M2Crypto/SSL/__init__.py -> build/lib.linux-x86_64-2.7/M2Crypt                              o/SSL                                                                                                 
  copying M2Crypto/SSL/timeout.py -> build/lib.linux-x86_64-2.7/M2Crypto                              /SSL                                                                                                  
  copying M2Crypto/SSL/Cipher.py -> build/lib.linux-x86_64-2.7/M2Crypto/                              SSL                                                                                                   
  copying M2Crypto/SSL/Connection.py -> build/lib.linux-x86_64-2.7/M2Cry                              pto/SSL                                                                                               
  copying M2Crypto/SSL/SSLServer.py -> build/lib.linux-x86_64-2.7/M2Cryp                              to/SSL                                                                                                
  copying M2Crypto/SSL/ssl_dispatcher.py -> build/lib.linux-x86_64-2.7/M                              2Crypto/SSL                                                                                           
  running build_ext                                                                                   
  building 'M2Crypto._m2crypto' extension                                                             
  swigging SWIG/_m2crypto.i to SWIG/_m2crypto_wrap.c                                                  
  swig -python -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/in                              clude -I/usr/include/x86_64-linux-gnu -I/usr/include -D__x86_64__ -I/usr                              /include/python2.7 -I/usr/include/openssl -includeall -modern -builtin -                              outdir /tmp/pip-install-K3Qabx/m2crypto/M2Crypto -o SWIG/_m2crypto_wrap.                              c SWIG/_m2crypto.i                                                                                    
  Deprecated command line option: -modern. This option is now always on.                              
  creating build/temp.linux-x86_64-2.7                                                                
  creating build/temp.linux-x86_64-2.7/SWIG                                                           
  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORT                              IFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-uC7NI8/python2.7-2.7                              .18=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I                              /usr/include/python2.7 -I/tmp/pip-install-K3Qabx/m2crypto/SWIG -c SWIG/_                              m2crypto_wrap.c -o build/temp.linux-x86_64-2.7/SWIG/_m2crypto_wrap.o -Wn                              o-deprecated-declarations -DTHREADING                                                                 
  SWIG/_m2crypto_wrap.c:156:11: fatal error: Python.h: No such file or d                              irectory                                                                                              
    156 | # include <Python.h>                                                                        
        |           ^~~~~~~~~~                                                                        
  compilation terminated.                                                                             
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1                                     
  ----------------------------------------                                                            
  ERROR: Failed building wheel for m2crypto
  Running setup.py clean for m2crypto
Failed to build m2crypto
Installing collected packages: m2crypto, apk-parse-ph4
    Running setup.py install for m2crypto ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -u -c 'import sys, setuptools, tokenize;                               sys.argv[0] = '"'"'/tmp/pip-install-K3Qabx/m2crypto/setup.py'"'"'; __fil                              e__='"'"'/tmp/pip-install-K3Qabx/m2crypto/setup.py'"'"';f=getattr(tokeni                              ze, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"'                              , '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'                               install --record /tmp/pip-record-Y3r4B_/install-record.txt --single-ver                              sion-externally-managed --compile --install-headers /usr/local/include/p                              ython2.7/m2crypto                                                                                     
         cwd: /tmp/pip-install-K3Qabx/m2crypto/                                                       
    Complete output (58 lines):                                                                       
    running install                                                                                   
    running build                                                                                     
    running build_py                                                                                  
    creating build                                                                                    
    creating build/lib.linux-x86_64-2.7                                                               
    creating build/lib.linux-x86_64-2.7/M2Crypto                                                      
    copying M2Crypto/m2.py -> build/lib.linux-x86_64-2.7/M2Crypto                                     
    copying M2Crypto/X509.py -> build/lib.linux-x86_64-2.7/M2Crypto                                   
    copying M2Crypto/threading.py -> build/lib.linux-x86_64-2.7/M2Crypto                              
    copying M2Crypto/DH.py -> build/lib.linux-x86_64-2.7/M2Crypto                                     
    copying M2Crypto/util.py -> build/lib.linux-x86_64-2.7/M2Crypto                                   
    copying M2Crypto/six.py -> build/lib.linux-x86_64-2.7/M2Crypto                                    
    copying M2Crypto/ftpslib.py -> build/lib.linux-x86_64-2.7/M2Crypto                                
    copying M2Crypto/m2urllib.py -> build/lib.linux-x86_64-2.7/M2Crypto                               
    copying M2Crypto/__init__.py -> build/lib.linux-x86_64-2.7/M2Crypto                               
    copying M2Crypto/callback.py -> build/lib.linux-x86_64-2.7/M2Crypto                               
    copying M2Crypto/m2urllib2.py -> build/lib.linux-x86_64-2.7/M2Crypto                              
    copying M2Crypto/DSA.py -> build/lib.linux-x86_64-2.7/M2Crypto                                    
    copying M2Crypto/Err.py -> build/lib.linux-x86_64-2.7/M2Crypto                                    
    copying M2Crypto/m2xmlrpclib.py -> build/lib.linux-x86_64-2.7/M2Cryp                              to                                                                                                    
    copying M2Crypto/AuthCookie.py -> build/lib.linux-x86_64-2.7/M2Crypt                              o                                                                                                     
    copying M2Crypto/RC4.py -> build/lib.linux-x86_64-2.7/M2Crypto                                    
    copying M2Crypto/m2crypto.py -> build/lib.linux-x86_64-2.7/M2Crypto                               
    copying M2Crypto/Rand.py -> build/lib.linux-x86_64-2.7/M2Crypto                                   
    copying M2Crypto/EVP.py -> build/lib.linux-x86_64-2.7/M2Crypto                                    
    copying M2Crypto/EC.py -> build/lib.linux-x86_64-2.7/M2Crypto                                     
    copying M2Crypto/httpslib.py -> build/lib.linux-x86_64-2.7/M2Crypto                               
    copying M2Crypto/RSA.py -> build/lib.linux-x86_64-2.7/M2Crypto                                    
    copying M2Crypto/SMIME.py -> build/lib.linux-x86_64-2.7/M2Crypto                                  
    copying M2Crypto/ASN1.py -> build/lib.linux-x86_64-2.7/M2Crypto                                   
    copying M2Crypto/BIO.py -> build/lib.linux-x86_64-2.7/M2Crypto                                    
    copying M2Crypto/Engine.py -> build/lib.linux-x86_64-2.7/M2Crypto                                 
    copying M2Crypto/BN.py -> build/lib.linux-x86_64-2.7/M2Crypto                                     
    creating build/lib.linux-x86_64-2.7/M2Crypto/SSL                                                  
    copying M2Crypto/SSL/TwistedProtocolWrapper.py -> build/lib.linux-x8                              6_64-2.7/M2Crypto/SSL                                                                                 
    copying M2Crypto/SSL/Session.py -> build/lib.linux-x86_64-2.7/M2Cryp                              to/SSL                                                                                                
    copying M2Crypto/SSL/Checker.py -> build/lib.linux-x86_64-2.7/M2Cryp                              to/SSL                                                                                                
    copying M2Crypto/SSL/Context.py -> build/lib.linux-x86_64-2.7/M2Cryp                              to/SSL                                                                                                
    copying M2Crypto/SSL/cb.py -> build/lib.linux-x86_64-2.7/M2Crypto/SS                              L                                                                                                     
    copying M2Crypto/SSL/__init__.py -> build/lib.linux-x86_64-2.7/M2Cry                              pto/SSL                                                                                               
    copying M2Crypto/SSL/timeout.py -> build/lib.linux-x86_64-2.7/M2Cryp                              to/SSL                                                                                                
    copying M2Crypto/SSL/Cipher.py -> build/lib.linux-x86_64-2.7/M2Crypt                              o/SSL                                                                                                 
    copying M2Crypto/SSL/Connection.py -> build/lib.linux-x86_64-2.7/M2C                              rypto/SSL                                                                                             
    copying M2Crypto/SSL/SSLServer.py -> build/lib.linux-x86_64-2.7/M2Cr                              ypto/SSL                                                                                              
    copying M2Crypto/SSL/ssl_dispatcher.py -> build/lib.linux-x86_64-2.7                              /M2Crypto/SSL                                                           
    running build_ext                                                   
    building 'M2Crypto._m2crypto' extension                             
    swigging SWIG/_m2crypto.i to SWIG/_m2crypto_wrap.c                  
    swig -python -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include -D__x86_64__ -I/usr/include/python2.7 -I/usr/include/openssl -includeall -modern -builtin -outdir /tmp/pip-install-K3Qabx/m2crypto/M2Crypto -o SWIG/_m2crypto_wrap.c SWIG/_m2crypto.i                                                    
    Deprecated command line option: -modern. This option is now always on.                                                                      
    creating build/temp.linux-x86_64-2.7                                
    creating build/temp.linux-x86_64-2.7/SWIG                           
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-uC7NI8/python2.7-2.7.18=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -I/tmp/pip-install-K3Qabx/m2crypto/SWIG -c SWIG/_m2crypto_wrap.c -o build/temp.linux-x86_64-2.7/SWIG/_m2crypto_wrap.o -Wno-deprecated-declarations -DTHREADING                                 
    SWIG/_m2crypto_wrap.c:156:11: fatal error: Python.h: No such file or directory                                                              
      156 | # include <Python.h>                                        
          |           ^~~~~~~~~~                                        
    compilation terminated.                                             
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1     
    ----------------------------------------                            
ERROR: Command errored out with exit status 1: /usr/bin/python2 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-K3Qabx/m2crypto/setup.py'"'"'; __file__='"'"'/tmp/pip-install-K3Qabx/m2crypto/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-Y3r4B_/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python2.7/m2crypto Check the logs for full command output.  


please help me

**Comment by dwisiswant0** [comment]
Hi, now APKLeaks is released version 2 (that supports Python3). Please give it try! No more this kinds of issues.
