### ISSUE TITLE
Publish source tarball on pypi?

### ISSUE THREAD

**Issue by chenrui333** [dwisiswant0/apkleaks#79]
👋 it looks like there is no source tarball for pypi for the latest release, do you mind publishing one over there (it would help homebrew to parsing out the dependencies). Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/153406

**Comment by dwisiswant0** [comment]
Hi, it's there now - https://pypi.org/project/apkleaks/2.6.1/#files

**Comment by chenrui333** [comment]
thank you!
