### ISSUE TITLE
swig error

### ISSUE THREAD

**Issue by EstherZurita** [dwisiswant0/apkleaks#9]
hello, everyone, i have this problem

building 'M2Crypto._m2crypto' extension
    swigging SWIG/_m2crypto.i to SWIG/_m2crypto_wrap.c
    C:\swigwin-3.0.12\swig.exe -python -Ic:\python27\include -Ic:\python27\PC -I/usr/include/openssl -includeall -modern -builtin -outdir c:\users\public\documents\wondershare\creatortemp\pip-build-n3nlsa\m2crypto\M2Crypto -o SWIG/_m2crypto_wrap.c SWIG/_m2crypto.i
    SWIG\_m2crypto.i(62) : Error: Unable to find 'openssl\opensslv.h'
    SWIG\_m2crypto.i(68) : Error: Unable to find 'openssl\safestack.h'
    SWIG\_evp.i(12) : Error: Unable to find 'openssl\opensslconf.h'
    SWIG\_rc4.i(5) : Error: Unable to find 'openssl\opensslconf.h'
    SWIG\_ec.i(7) : Error: Unable to find 'openssl\opensslconf.h'
    error: command 'C:\\swigwin-3.0.12\\swig.exe' failed with exit status 1

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\public\\documents\\wondershare\\creatortemp\\pip-build-n3nlsa\\m2crypto\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\public\documents\wondershare\creatortemp\pip-j9duqt-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\public\documents\wondershare\creatortemp\pip-build-n3nlsa\m2crypto\

however I have wig and openssl installed correctly

C:\>openssl
OpenSSL>

please help me

**Comment by dwisiswant0** [comment]
Hi @EstherZurita, now APKLeaks is released version 2 (that supports Python3). Please give it try!
